repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      #- id: pretty-format-json
      #  args: [--autofix]
      - id: sort-simple-yaml
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: debug-statements
      - id: check-yaml
        args: ['--unsafe']
      - id: check-xml
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-ast

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff-check
        files: \.ipynb$  # Only process .ipynb files
        additional_dependencies: [ruff, jupytext]
        args: ["--line-length=120", "--ignore=I001"]

      - id: nbqa-ruff-format
        files: \.ipynb$  # Only process .ipynb files
        additional_dependencies: [ruff, jupytext]
        args: ["--line-length=120"]

  # Jupytext: Sync .ipynb with paired .py files and clean metadata
  - repo: local
    hooks:
      - id: jupytext-sync
        name: Jupytext Sync
        entry: |
           jupytext --sync
        language: python
        files: \.ipynb$  # Target only Jupyter Notebooks
        types: [file]
        additional_dependencies: [jupytext, black]  # Install deps automatically

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        files: \.ipynb$
